create a numpy array using a list.

In [2]:
import numpy as np

a= np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


create a 2d array uisng numpy

In [4]:
import numpy as np

a= np.array([[1,2,3,4,5],[23,45,6,0, 5]])
# dimentions should be same
print(a)


[[ 1  2  3  4  5]
 [23 45  6  0  5]]


Attributes of an array

In [2]:
import numpy as np

a= np.array([[1,2,3,4,5],[23,45,6,0, 5]])
# dimentions should be same
print(a)
print(a.ndim)  # no of dimensions
print(a.shape) # shape of array (2,5) tuple type
print(a.size)  # total no of elements
print(a.dtype) # data type of array elements - int64

[[ 1  2  3  4  5]
 [23 45  6  0  5]]
2
(2, 5)
10
int64


Broadcasting operation- pass one element operate it with all elements of an array (no loop requiredd-fasterr)

Create two vectors : x and y and perform addion operation on these vectors

In [4]:
import numpy as np

x = np.array([1,2,3,4,5])
y = np.array([1,2,3,4,5])
c = x + y
c


array([ 2,  4,  6,  8, 10])

ZEROSSS, ONESS, EYE: (identity matrix)

In [9]:
import numpy as np

z = np.zeros((4,7))
o = np.ones((4,7))
e = np.eye((3)) #created identity matrix
print(z)
print(o)
print(e)

# coool feature lol
m = z>0
print(m)

print(np.logical_not(e))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]]
[[False  True  True]
 [ True False  True]
 [ True  True False]]
